using System.Reflection;
using MicroKit.Domain.Identifiers;
using SaasBtp.Access.Domain.Identity;
using SaasBtp.Access.Domain.Organizations;
using SaasBtp.Access.Domain.Workspaces;
using Shouldly;
using Xunit;

namespace SaasBtp.Access.Domain.UnitTests;

/// <summary>
/// Identity behaviour shared by every domain identifier: UUIDv7, generated by the domain, and
/// compared by value (conventions/naming.md). Three identifiers are minted here — two aggregate
/// roots and the one internal component that keeps an identity of its own.
/// </summary>
public sealed class TypedIdentityTests
{
    public static TheoryData<IEntityId> DomainGeneratedIds() =>
    [
        OrganizationId.New(),
        WorkspaceId.New(),
        WorkspaceAccessId.New(),
    ];

    [Theory]
    [MemberData(nameof(DomainGeneratedIds))]
    public void Domain_generated_ids_are_uuid_v7(IEntityId id)
        => ((Guid)id.Value!).Version.ShouldBe(7);

    [Theory]
    [MemberData(nameof(DomainGeneratedIds))]
    public void Domain_generated_ids_are_not_empty(IEntityId id)
        => ((Guid)id.Value!).ShouldNotBe(Guid.Empty);

    [Fact]
    public void The_access_edge_born_with_a_workspace_carries_a_uuid_v7_identity()
    {
        // The edge must survive its own revocation without destroying history (Implementation
        // Design §3.5), so it is the one internal component that has an identity — and it is a
        // domain-generated UUIDv7 like the roots', not a database sequence.
        var workspace = Workspace.Found(
            OrganizationId.New(), "Agence Cocody",
            new PersonId(Guid.CreateVersion7()),
            new DateTime(2026, 8, 16, 10, 30, 0, DateTimeKind.Utc));

        var accessId = workspace.Accesses.Single().Id;

        accessId.Value.Version.ShouldBe(7);
        accessId.Value.ShouldNotBe(Guid.Empty);
    }

    [Fact]
    public void New_yields_a_distinct_value_each_time()
        => OrganizationId.New().ShouldNotBe(OrganizationId.New());

    [Fact]
    public void Ids_compare_by_value()
    {
        var value = Guid.CreateVersion7();

        new OrganizationId(value).ShouldBe(new OrganizationId(value));
        new PersonId(value).ShouldBe(new PersonId(value));
    }

    [Fact]
    public void A_person_identity_is_received_from_the_auth_boundary_never_minted_by_the_domain()
    {
        // The absence of PersonId.New() is the statement: GoTrue owns the identity, this domain
        // only names it. A factory here would let the domain invent people.
        typeof(PersonId).GetMethod("New", BindingFlags.Public | BindingFlags.Static)
            .ShouldBeNull();
    }
}
