-- 0004_site_model.sql
-- Owner: DbUp (ADR-ARCH-006). DbUp is the single authority for this schema; EF Core maps schemas it
-- owns, never creates them (site.* has no EF mapping — the scope provider reads it with plain Npgsql).
-- Applied by tools/database-migrator with the privileged owner role.
--
-- PORTABLE script: references NO GoTrue role or table, no `auth` schema object, so the anti-drift
-- Testcontainer harness runs it on bare Postgres (conventions/sql.md §Auth-coupled scripts). It is
-- therefore NOT listed in MigrationRunner.AuthCoupledScriptMarkers.
--
-- THE MODEL (authorization model, ADR-ARCH-009). Two INDEPENDENT authorization edges:
--   * access.memberships (0002)     user -> tenant   (organization edge)
--   * site.site_memberships (here)  user -> site     (site edge)
-- Neither implies the other: an external subcontractor / inspector holds a site edge with NO tenant
-- edge in the site's tenant. Authorization is DATA queried per request over these tables; the
-- role -> scope matrix lives in C# (ISiteScopeProvider), NOT in the DB — there is no permissions,
-- roles, or role_permissions table.

-- First table of the Site context's DB surface: create its schema just-in-time (sql.md §Casing & naming).
CREATE SCHEMA IF NOT EXISTS site;

-- ---------------------------------------------------------------------------------------------------
-- site.sites — a construction site (chantier), scoped to a tenant.
-- ---------------------------------------------------------------------------------------------------
CREATE TABLE site.sites (
    id          uuid          NOT NULL,
    tenant_id   uuid          NOT NULL,
    name        varchar(200)  NOT NULL,
    status      varchar(20)   NOT NULL,
    created_at  timestamptz   NOT NULL,

    -- id is a UUIDv7 generated by the domain at creation (naming.md); NO DB default. created_at is
    -- NOT NULL with NO default — domain-stamped (ADR-ARCH-005), exactly as access.tenants /
    -- safety.constats. A DB default (now()) would MASK a domain that forgot to stamp it, instead of
    -- failing loudly at INSERT.
    CONSTRAINT pk_sites PRIMARY KEY (id),

    -- tenant_id is denormalized and carries NO FK: access.tenants lives in another bounded context, and
    -- app DDL never crosses a context boundary with a foreign key (precedent: safety.constats.tenant_id,
    -- 0001). The "site belongs to tenant" link is a domain invariant enforced on the write path, not a
    -- cross-context constraint. name width matches access.tenants.name / access.profiles.full_name (200):
    -- the same class of human-entered organizational display name.

    -- Closed set: the lifecycle of the site. Lowercase snake_case token + CHECK (sql.md §Closed sets);
    -- the domain Value Object is the source of truth, this CHECK is defense-in-depth. NOTE: NOTHING reads
    -- status in this increment — "a closed site rejects constats" is explicitly NOT a constat invariant
    -- (safety-domain-model). The token is frozen now so the grain is fixed; enforcement is a later issue.
    CONSTRAINT ck_sites__status CHECK (status IN ('active', 'closed')),

    -- Exists SOLELY to be the matching target of the composite FK from site_memberships (id, tenant_id).
    -- id alone is already unique via pk_sites; Postgres requires an FK's referenced columns to match a
    -- UNIQUE/PK on EXACTLY (id, tenant_id), which the single-column PK does not provide. This is NOT a
    -- redundant read-path index (the #45 lesson) — its purpose is referential integrity; the anti-drift
    -- test asserts it PRESENT.
    CONSTRAINT ux_sites__id_tenant_id UNIQUE (id, tenant_id)
);

-- RLS enabled, NO policy: the owner (migrator/app) bypasses RLS and is the only consumer today; the
-- non-owner read policy (PowerSync) is #50. RLS-on/no-policy returns ZERO ROWS SILENTLY to every
-- non-bypassing role by default (sql.md §RLS) — so the day a non-privileged consumer touches this table
-- a policy becomes MANDATORY (the #45 lesson).
ALTER TABLE site.sites ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------------------------------
-- site.site_memberships — the site edge: "user U works on site S". Independent of the org edge, so it
-- can exist ALONE (an external person with no membership in the site's tenant).
-- ---------------------------------------------------------------------------------------------------
CREATE TABLE site.site_memberships (
    id                uuid          NOT NULL,
    site_id           uuid          NOT NULL,
    tenant_id         uuid          NOT NULL,
    user_id           uuid          NOT NULL,
    origin_tenant_id  uuid          NULL,
    role              varchar(20)   NOT NULL,
    is_active         boolean       NOT NULL,
    valid_from        timestamptz   NOT NULL,
    valid_until       timestamptz   NULL,
    created_at        timestamptz   NOT NULL,

    -- id + created_at: UUIDv7 + domain-stamped, NO defaults (as access.memberships). is_active NOT NULL,
    -- NO default — the domain sets it explicitly at creation; an implicit default would hide the choice.
    -- valid_from is the BUSINESS start of the assignment, domain-stamped: the occurred_at vs created_at
    -- distinction from Safety (when the mission begins vs when the row was written).
    CONSTRAINT pk_site_memberships PRIMARY KEY (id),

    -- user_id carries NO FK to access.profiles: cross-bounded-context (precedent as above). This is
    -- precisely what lets an EXTERNAL person hold a site edge with no presence in the Access context.

    -- origin_tenant_id is the tenant the person COMES FROM. = tenant_id -> internal; <> tenant_id ->
    -- external (a subcontractor from another organization); NULL -> independent / unknown. NO FK, NO
    -- CHECK — externality is a RELATIONAL FACT read on the query path, not a role or a constraint. It
    -- exists from day one because it CANNOT be retrofitted: once memberships are created without it, the
    -- origin is lost.

    -- Composite FK ON PURPOSE: referencing (site_id, tenant_id) makes the denormalized tenant_id
    -- physically unable to diverge from the site's tenant. Intra-context (both tables in schema site), so
    -- the cross-bounded-context / auth FK ban does NOT apply. NO CASCADE — a membership is
    -- insert-then-deactivate (is_active), never hard-deleted as a DB side effect; lifecycle is a
    -- deliberate domain operation (ADR-ARCH-005).
    CONSTRAINT fk_site_memberships__sites
        FOREIGN KEY (site_id, tenant_id) REFERENCES site.sites (id, tenant_id),

    -- Closed set: the role WITHIN the site. Lowercase snake_case token + CHECK (sql.md §Closed sets);
    -- the domain VO is the source of truth. Deliberately minimal — adding a token later is a one-line
    -- append-only migration. The GRAIN is frozen here, the VALUES are not.
    CONSTRAINT ck_site_memberships__role CHECK (role IN ('site_manager', 'member')),

    -- One relation = one role: a user holds at most one role on a given site. Moving to N roles later
    -- means DROPPING this unique — append-only, lossless. This unique index's B-tree also answers
    -- site-scoped lookups by its LEFT PREFIX (site_id), so no standalone site_id index is created.
    CONSTRAINT ux_site_memberships__site_id_user_id UNIQUE (site_id, user_id),

    -- valid_until is the PLANNED end of mission; distinct from is_active (immediate revocation): is_active
    -- = revoked, valid_until = the mission ended. If set, it must be strictly after valid_from.
    CONSTRAINT ck_site_memberships__valid_window CHECK (valid_until IS NULL OR valid_until > valid_from)
);

-- The user-first lookup index. This is the PowerSync parameter-query path
-- (WHERE user_id = request.user_id() -> "which sites does this user have?"): NO existing index's left
-- prefix is user_id (ux_site_memberships__site_id_user_id leads with site_id), so it needs its own. It is
-- NOT motivated by the provider's branch-(a) probe, which is an equality on BOTH user_id AND site_id and
-- is already served by ux_site_memberships__site_id_user_id. Mirrors ix_memberships__user_id in 0002.
CREATE INDEX ix_site_memberships__user_id ON site.site_memberships (user_id);

-- Deliberately NO ix_site_memberships__site_id and NO ix_site_memberships__tenant_id: both would be
-- redundant. site_id is the LEFT PREFIX of ux_site_memberships__site_id_user_id; the composite FK is
-- validated against the PARENT (ux_sites__id_tenant_id), so the child side needs no covering index (no
-- CASCADE). Either would only duplicate a prefix and slow writes for no read gain (the #45 lesson).

-- RLS enabled, NO policy (same rationale as site.sites above; the non-owner policy is #50).
ALTER TABLE site.site_memberships ENABLE ROW LEVEL SECURITY;
