-- 0005_access_invitations.sql
-- Owner: DbUp (ADR-ARCH-006). DbUp is the single authority for this schema; EF Core maps schemas it
-- owns, never creates them. Applied by tools/database-migrator with the privileged owner role.
--
-- PORTABLE script: references NO GoTrue role or table, no `auth` schema object, so the anti-drift
-- Testcontainer harness runs it on bare Postgres (conventions/sql.md §Auth-coupled scripts). It is
-- therefore NOT listed in MigrationRunner.AuthCoupledScriptMarkers.
--
-- THE MODEL (onboarding by invitation, ADR-ARCH-011). The invitation token IS the authorization to
-- exist in the product; it replaces, on the correct side of the boundary, what the removed auth.users
-- trigger used to guess. Two tables, each total, neither polymorphic:
--   * access.invitations       the onboarding workflow (NOT an authorization edge)
--   * access.invitation_sites  0..N site edges the invitation will grant, one row per site
-- STORAGE ONLY: neither table has a writer yet. Population starts with CreateInvitation /
-- AcceptInvitation (later steps of #48). The e-mail/outbox delivery table is a SEPARATE later
-- migration (MicroKit.Messaging), deliberately not here.

-- access schema already exists (0002); no CREATE SCHEMA here.

-- ---------------------------------------------------------------------------------------------------
-- access.invitations — the onboarding workflow. NOT an authorization edge: it records who was invited
-- by whom, to what, and how the workflow ended (accepted / revoked / — expired is derived).
-- ---------------------------------------------------------------------------------------------------
CREATE TABLE access.invitations (
    id           uuid          NOT NULL,
    email        varchar(255)  NOT NULL,
    token_hash   char(64)      NOT NULL,
    status       varchar(20)   NOT NULL,
    expires_at   timestamptz   NOT NULL,
    tenant_id    uuid          NOT NULL,
    tenant_role  varchar(20)   NULL,
    invited_by   uuid          NOT NULL,
    created_at   timestamptz   NOT NULL,
    accepted_at  timestamptz   NULL,

    -- id is a UUIDv7 generated by the domain at creation (naming.md); NO DB default. created_at and
    -- accepted_at are domain-stamped (ADR-ARCH-005), NO defaults — a DB default would mask a domain
    -- that forgot to stamp. accepted_at is NULL until AcceptInvitation sets it.
    CONSTRAINT pk_invitations PRIMARY KEY (id),

    -- token_hash is the SHA-256 (lowercase hex, what Convert.ToHexString(..).ToLowerInvariant()
    -- produces) of the clear token, NEVER the token itself: a dump of this table must not yield one
    -- usable invitation — the clear token lives only in the e-mail (ADR-ARCH-011 §Security). UNIQUE:
    -- the acceptance path is WHERE token_hash = ?, so this unique's implicit B-tree already serves it
    -- (no separate index). The token is a 32-byte CSPRNG secret, never a UUID (an identifier is not a
    -- secret).
    CONSTRAINT ux_invitations__token_hash UNIQUE (token_hash),

    -- Defense-in-depth on the hash SHAPE: exactly 64 lowercase hex chars. This makes '', 'abc', 'foo',
    -- an uppercased hash, or a leaked clear token structurally impossible — a length check alone would
    -- not pin the alphabet or the case. (On char(64) a short value is blank-padded, but the regex is
    -- applied to the padded text so spaces fail [0-9a-f]; and length() ignores trailing blanks anyway.)
    CONSTRAINT ck_invitations__token_hash_hex CHECK (token_hash ~ '^[0-9a-f]{64}$'),

    -- Closed set (sql.md §Closed sets); the domain VO is the source of truth, this CHECK is
    -- defense-in-depth. 'revoked' — NOT 'cancelled' — is the vocabulary already used for memberships
    -- (is_active = false). 'expired' is deliberately ABSENT: it is DERIVED (status = 'pending' AND
    -- expires_at < now()); storing it would need a job to keep it true — a second source of truth that
    -- can silently disagree.
    CONSTRAINT ck_invitations__status CHECK (status IN ('pending', 'accepted', 'revoked')),

    -- tenant_role mirrors access.memberships.role (0002). NULL means NO organization edge will be
    -- created at acceptance — i.e. THE INVITEE IS EXTERNAL (a subcontractor, an inspector). One column
    -- carries the whole distinction. Externality is a RELATIONAL FACT, not a role (ADR-ARCH-009): there
    -- is no 'sub_contractor' token, ever.
    CONSTRAINT ck_invitations__tenant_role
        CHECK (tenant_role IS NULL OR tenant_role IN ('owner', 'admin', 'member'))
);

-- email is stored NORMALIZED (lower(trim(email))): the DOMAIN normalizes before writing, the same
-- discipline as timestamps (ADR-ARCH-005). access.invitations has exactly ONE writer and it upholds the
-- invariant, so NO CITEXT and NO functional index (the same choice as ux_profiles__email, 0002).
-- varchar(255) is a COPY CONSTRAINT, NOT RFC 5321's theoretical maximum (320): AcceptInvitation copies
-- this value into access.profiles.email, which is varchar(255) (0002) and CANNOT be widened
-- (append-only). A 300-char address would pass HERE and FAIL at acceptance — a silent divergence on the
-- product's ONLY account-creation path. Real addresses above 255 do not exist; matching the DESTINATION
-- column is worth more than matching a theoretical maximum. Do NOT "fix" this to 320.
--
-- tenant_id carries NO FK and is NOT NULL: every invitation is issued BY a tenant, including one that
-- invites an external person — it is what the issuer's authorization is checked against (ADR-ARCH-011).
-- invited_by is the issuer's user_id, for audit ("who invited whom, when"), also NO FK.
-- Intentionally NO FK on tenant_id or invited_by: cross-bounded-context / auth boundary (precedent:
-- safety.constats.tenant_id, 0001; site.site_memberships.user_id, 0004). The invariants "the tenant
-- exists" and "the issuer is a real, authorized user" are enforced by the CreateInvitation command
-- (ADR-ARCH-011), not by the database.
--
-- expires_at is NOT NULL, NO default: every invitation expires; the 7-day validity is CONFIGURATION (a
-- product parameter), stamped by the domain — NOT a DDL `DEFAULT now() + interval` (ADR-ARCH-005).

-- AT MOST ONE LIVE INVITATION per (tenant, e-mail). Without it, an admin can mint several live tokens
-- for the same person in the same tenant — possibly with DIFFERENT tenant_role values — and the INVITEE
-- chooses which to accept: an invitee-driven privilege escalation, the exact family #45 closed. The
-- PARTIAL unique makes it structurally impossible: the constraint is the guard, not a domain rule
-- someone can forget to write. Scoped to status = 'pending', so it still ALLOWS re-inviting after
-- 'revoked' or 'accepted' (a person leaves and returns); it FORBIDS two live tokens at once. Re-inviting
-- therefore means REVOKE-then-CREATE in one transaction (CreateInvitation, a later step of #48) — the
-- previous token must die before a new one is minted.
CREATE UNIQUE INDEX ux_invitations__tenant_id_email__pending
    ON access.invitations (tenant_id, email)
    WHERE status = 'pending';

-- No OTHER index. The acceptance lookup (token_hash) is covered by ux_invitations__token_hash; a
-- standalone email or tenant_id read-path index ("pending invitations for this person", "invitations
-- issued by my company") has NO reader yet — the verify endpoint and GET /me/workspaces are LATER steps
-- of #48. An index with no reader is speculative and only slows writes (the #45 lesson); each is a
-- one-line append-only migration the day a real query needs it. (The partial unique above exists for the
-- CONSTRAINT, not a read path — its reader is the uniqueness guard itself.)

-- RLS enabled, NO policy: the privileged .NET owner bypasses RLS and is the only consumer today. With
-- RLS on and no policy, every non-bypassing role gets ZERO ROWS SILENTLY (sql.md §RLS) — not an error,
-- a silent empty read. A policy becomes MANDATORY the day a non-privileged consumer touches this table
-- (the #45 lesson); that is #50.
ALTER TABLE access.invitations ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------------------------------
-- access.invitation_sites — the 0..N site edges an invitation will grant, one row per site. MIRRORS
-- site.site_memberships (type + tokens + validity window) so acceptance is a COPY, not a translation.
-- ---------------------------------------------------------------------------------------------------
CREATE TABLE access.invitation_sites (
    invitation_id  uuid          NOT NULL,
    site_id        uuid          NOT NULL,
    site_role      varchar(20)   NOT NULL,
    valid_from     timestamptz   NOT NULL,
    valid_until    timestamptz   NULL,

    -- Natural composite PK: one site edge per (invitation, site). A person cannot be invited twice to
    -- the same site within one invitation, so the invariant IS the identity — the key is the guard, and
    -- no surrogate id and no separate unique are needed. invitation_sites is a child edge-COLLECTION of
    -- the Invitation aggregate (ADR-ARCH-011: "a site assignment is an edge COLLECTION, not part of the
    -- invitation's identity"), never addressed individually and with no inbound FK — unlike
    -- site.site_memberships, which is an authorization edge with its own per-request lifecycle (is_active)
    -- and therefore earns a surrogate id. The PK's left prefix (invitation_id) also answers the only read
    -- path — "all sites for this invitation" at acceptance — so no standalone index is created.
    CONSTRAINT pk_invitation_sites PRIMARY KEY (invitation_id, site_id),

    -- The ONLY FK in this script, and intra-context (both tables in schema access), so the
    -- cross-context / auth FK ban does not apply. ON DELETE RESTRICT, NOT CASCADE: an invitation is
    -- NEVER deleted — it is the audit trail ("Jean invited Paul on 3 March; Paul never answered");
    -- revocation is status = 'revoked', not a DELETE (ADR-ARCH-011). A CASCADE would exist for exactly
    -- one purpose — to make an ACCIDENTAL parent delete succeed silently; RESTRICT makes it FAIL. The
    -- constraint is the guard, not the comment.
    CONSTRAINT fk_invitation_sites__invitations
        FOREIGN KEY (invitation_id) REFERENCES access.invitations (id) ON DELETE RESTRICT,

    -- site_id carries NO FK. Intentionally NO FK: cross-bounded-context (precedent:
    -- safety.constats.site_id, 0001; site.site_memberships.user_id, 0004). The invariant "the site
    -- exists AND belongs to tenant_id" is enforced by the CreateInvitation command (ADR-ARCH-011), not
    -- by the database.

    -- site_role mirrors site.site_memberships.role (0004). Closed set (sql.md §Closed sets); the domain
    -- VO is the source of truth, this CHECK is defense-in-depth.
    CONSTRAINT ck_invitation_sites__site_role
        CHECK (site_role IN ('site_manager', 'member')),

    -- valid_from is the BUSINESS start of the assignment (domain-stamped, NO default); valid_until is the
    -- PLANNED end of mission. If set, it must be strictly after valid_from. Same shape as
    -- ck_site_memberships__valid_window (0004), so acceptance copies both columns verbatim.
    CONSTRAINT ck_invitation_sites__valid_window
        CHECK (valid_until IS NULL OR valid_until > valid_from)
);

-- Deliberately NO ix_invitation_sites__site_id: it would be redundant. The sole read path is
-- "all sites for this invitation", served by the PK's LEFT PREFIX (invitation_id). site_id has no
-- reader of its own (it is copied into site.site_memberships at acceptance, then read THERE). A
-- standalone site_id index would only slow writes (the #45 lesson).

-- RLS enabled, NO policy (same rationale as access.invitations above; the non-owner policy is #50).
ALTER TABLE access.invitation_sites ENABLE ROW LEVEL SECURITY;
