name: CI API

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  api-build-test:
    name: api-build-test
    runs-on: ubuntu-latest
    steps:
      - name: Required-check-demo
        run: exit 1

      - name: Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up the .NET SDK from global.json
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore SaasBtp.slnx

      - name: Build (Release)
        run: dotnet build SaasBtp.slnx -c Release --no-restore

      - name: Test (Release)
        run: dotnet test SaasBtp.slnx -c Release --no-build
